name: open-build-test
on: workflow_dispatch
env:
  REPO_URL: https://github.com/zzzzzhy/speedtest-cpp.git
  REPO_BRANCH: master

jobs:
  build:
    name: Build ${{ matrix.arch }} ipk
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - mips_24kc
          - mipsel_24kc
          - mvebu-cortexa53
          - x86_64
        version: [19.07.7]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: innet8/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.version }}
          MODE: open
          DEPENDENCES: libcurl libxml2 libopenssl libstdcpp
          ADDR: ${{ env.REPO_URL }}
          BRANCH: ${{ env.REPO_BRANCH }}
          PKG: speedtest-cpp

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: "*.ipk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
